### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/Background#400]
```[tasklist]
### Todo
- [x] Localize package.json + commands
- [ ] Localize extension strings
- [x] Set up string replacer
- [ ] Replacer implementation
- [x] Guidelines for locale PRs
- [x] Guidelines for locale issues
```

Need to consider # + s case

Enums should use English values, but have localized display name
